# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/INTRA/eydire/workspace/project/week2vivado/week2.cache/wt [current_project]
set_property parent.project_path /home/INTRA/eydire/workspace/project/week2vivado/week2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  /home/INTRA/eydire/workspace/project/vivado/ip_repo/myip_1.0
  /home/INTRA/eydire/workspace/project/vivado/ip_repo/AXI_to_audio_1.0
  /home/INTRA/eydire/workspace/project/vivado/ip_repo/audio_to_AXI_1.0
  /home/INTRA/eydire/workspace/project/ip_repo/ip_repo_vivado
  /home/INTRA/eydire/workspace/project/ip_repo/zedboard_audio
  /home/INTRA/eydire/workspace/project/ip_repo/Audio_Mixer
} [current_project]
add_files /home/INTRA/eydire/workspace/project/week2vivado/week2.srcs/sources_1/bd/week1/week1.bd
set_property used_in_implementation false [get_files -all /home/INTRA/eydire/workspace/project/week2vivado/week2.srcs/sources_1/bd/week1/ip/week1_processing_system7_0_0/week1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/eydire/workspace/project/week2vivado/week2.srcs/sources_1/bd/week1/ip/week1_rst_processing_system7_0_100M_0/week1_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/eydire/workspace/project/week2vivado/week2.srcs/sources_1/bd/week1/ip/week1_rst_processing_system7_0_100M_0/week1_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/eydire/workspace/project/week2vivado/week2.srcs/sources_1/bd/week1/ip/week1_rst_processing_system7_0_100M_0/week1_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/eydire/workspace/project/week2vivado/week2.srcs/sources_1/bd/week1/ip/week1_xbar_0/week1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/eydire/workspace/project/week2vivado/week2.srcs/sources_1/bd/week1/ip/week1_auto_pc_0/week1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/eydire/workspace/project/week2vivado/week2.srcs/sources_1/bd/week1/week1_ooc.xdc]
set_property is_locked true [get_files /home/INTRA/eydire/workspace/project/week2vivado/week2.srcs/sources_1/bd/week1/week1.bd]

read_vhdl -library xil_defaultlib /home/INTRA/eydire/workspace/project/week2vivado/week2.srcs/sources_1/bd/week1/hdl/week1_wrapper.vhd
read_xdc /home/INTRA/eydire/workspace/project/ip_repo/zedboard_audio/constraints/zed_audio.xdc
set_property used_in_implementation false [get_files /home/INTRA/eydire/workspace/project/ip_repo/zedboard_audio/constraints/zed_audio.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top week1_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef week1_wrapper.dcp
catch { report_utilization -file week1_wrapper_utilization_synth.rpt -pb week1_wrapper_utilization_synth.pb }
